/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *page_d_acceuil;
  GtkWidget *gestion_liste_erlectorale_A;
  GtkWidget *gestion_liste_erlectorale_B;
  GtkWidget *gestion_liste_erlectorale_C;
  GtkWidget *gestion_de_liste_electorale_ajout;
  GtkWidget *Tab_user;
  GtkWidget *tab_obs;
  GtkWidget *ajout_user;
  GtkWidget *gestion_des_elections;
  GtkWidget *ajout_election;
  GtkWidget *modifier_supprimer_election;
  GtkWidget *ajouter_une_reclamation;
  GtkWidget *modifier_une_reclamation;
  GtkWidget *gestion_bv;
  GtkWidget *tab_BV;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  page_d_acceuil = create_page_d_acceuil ();
  gtk_widget_show (page_d_acceuil);
  gestion_liste_erlectorale_A = create_gestion_liste_erlectorale_A ();
  gtk_widget_show (gestion_liste_erlectorale_A);
  gestion_liste_erlectorale_B = create_gestion_liste_erlectorale_B ();
  gtk_widget_show (gestion_liste_erlectorale_B);
  gestion_liste_erlectorale_C = create_gestion_liste_erlectorale_C ();
  gtk_widget_show (gestion_liste_erlectorale_C);
  gestion_de_liste_electorale_ajout = create_gestion_de_liste_electorale_ajout ();
  gtk_widget_show (gestion_de_liste_electorale_ajout);
  Tab_user = create_Tab_user ();
  gtk_widget_show (Tab_user);
  tab_obs = create_tab_obs ();
  gtk_widget_show (tab_obs);
  ajout_user = create_ajout_user ();
  gtk_widget_show (ajout_user);
  gestion_des_elections = create_gestion_des_elections ();
  gtk_widget_show (gestion_des_elections);
  ajout_election = create_ajout_election ();
  gtk_widget_show (ajout_election);
  modifier_supprimer_election = create_modifier_supprimer_election ();
  gtk_widget_show (modifier_supprimer_election);
  ajouter_une_reclamation = create_ajouter_une_reclamation ();
  gtk_widget_show (ajouter_une_reclamation);
  modifier_une_reclamation = create_modifier_une_reclamation ();
  gtk_widget_show (modifier_une_reclamation);
  gestion_bv = create_gestion_bv ();
  gtk_widget_show (gestion_bv);
  tab_BV = create_tab_BV ();
  gtk_widget_show (tab_BV);

  gtk_main ();
  return 0;
}

